updates

diff --git a/roles/prometheus/templates/init.service.j2 b/roles/prometheus/templates/init.service.j2
--- a/roles/prometheus/templates/init.service.j2
+++ b/roles/prometheus/templates/init.service.j2
@@ -1,16 +1,63 @@
-[Unit]
-Description={{serviceName}}
-Wants=network-online.target
-After=network-online.target
+#!/bin/bash
+# myapp daemon
+# chkconfig: 345 20 80
+# description: myapp daemon
 
-[Service]
-User={{ userId }}
-Group={{ groupId }}
-Restart=always
-RestartSec=2
-StartLimitInterval=0
-Type=simple
-ExecStart={{ exec_command }}
+DAEMON_PATH="/etc/init.d/"
 
-[Install]
-WantedBy=multi-user.target
+DAEMON={{serviceName}}
+DAEMONOPTS="--config.file=/etc/prometheus/prometheus.conf --storage.tsdb.path=/data/prometheus --storage.tsdb.retention=2d"
+
+NAME={{serviceName}}
+DESC="My {{serviceName}} description"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
+
+case "$1" in
+start)
+	printf "%-50s" "Starting $NAME..."
+	cd $DAEMON_PATH
+	PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
+	#echo "Saving PID" $PID " to " $PIDFILE
+        if [ -z $PID ]; then
+            printf "%s\n" "Fail"
+        else
+            echo $PID > $PIDFILE
+            printf "%s\n" "Ok"
+        fi
+;;
+status)
+        printf "%-50s" "Checking $NAME..."
+        if [ -f $PIDFILE ]; then
+            PID=`cat $PIDFILE`
+            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
+                printf "%s\n" "Process dead but pidfile exists"
+            else
+                echo "Running"
+            fi
+        else
+            printf "%s\n" "Service not running"
+        fi
+;;
+stop)
+        printf "%-50s" "Stopping $NAME"
+            PID=`cat $PIDFILE`
+            cd $DAEMON_PATH
+        if [ -f $PIDFILE ]; then
+            kill -HUP $PID
+            printf "%s\n" "Ok"
+            rm -f $PIDFILE
+        else
+            printf "%s\n" "pidfile not found"
+        fi
+;;
+
+restart)
+  	$0 stop
+  	$0 start
+;;
+
+*)
+        echo "Usage: $0 {status|start|stop|restart}"
+        exit 1
+esac
